# Model arguments
model_name_or_path: meta-llama/Meta-Llama-3.1-70B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_mixer:
  /home/mdr2rng/llm-data/vm-test-dev-assistant/multiple_requirements_and_test_specifications: 1.0
  /home/mdr2rng/llm-data/vm-test-dev-assistant/fd_qa: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 12

# SFT trainer config
bf16: true
#dataset_kwargs:
#  add_special_tokens: false  # We already wrap <bos> and <eos> in the chat template
#  append_concat_token: false # No need to add <eos> across samples
do_eval: true
eval_strategy: epoch
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: zephyr-7b-gemma-sft
hub_strategy: every_save
learning_rate: 2.0e-05
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 8192
max_steps: -1
num_train_epochs: 5
output_dir: data/llama-3.1-70b-instruct-vm-full-1
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
push_to_hub: false
remove_unused_columns: true
report_to:
- tensorboard
- wandb
save_strategy: "steps"
save_steps: 100
save_total_limit: 1
seed: 42
warmup_ratio: 0.1